server:
  port: 8080
  servlet:
    context-path: /n2
    session:
      timeout: 30m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Hjgark1012
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
