server:
  port: 8080
  servlet:
    context-path: /n2
    session:
      timeout: 30m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloudinary:
    cloud_name: djhqmrh8s
    api_key: 919464163916169
    api_secret: HFELZJ64z4oGuhcxNh8vV48ldts


